name: KI Cadence Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - gpavlov/update-github-actions-workflow
      - gpavlov/setup-cypress

jobs:
  jest:
    name: Build on Emulator and Test Cadence
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.16"]
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Flow CLI
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

      - name: Update PATH
        run: echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: Root NPM Install
        run: npm i fs-jetpack chalk && npm i && npx lerna exec npm install

      - name: Run JS Tests
        run: npm i && npm run test
        working-directory: cadence/tests

      - name: Build & Run
        run: npm run dev:emulator & sleep 30

      - name: Deploy Contracts
        run: flow project deploy --network=emulator --update

  windows-build:
    name: Build on Windows
    timeout-minutes: 10
    runs-on: windows-latest
    strategy:
      matrix:
        go: ["1.16"]
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Flow CLI
        run: iex "& { $(irm 'https://storage.googleapis.com/flow-cli/install.ps1') }"

      - name: Update PATH
        run: echo "/root/.local/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Checkout
        uses: actions/checkout@v2

      - name: Root NPM Install
        run: npm i fs-jetpack chalk && npm i && npx lerna exec npm install

      - name: Build & Run
        run: npm run dev:emulator & sleep 30